language: python
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install python-coveralls pytest-cov tox tox-travis
script: tox --recreate
after_success:
- pip install -e .
- py.test --cov=envoy_webhook_auth_decorator --cov-report=term-missing tests
- coveralls
deploy:
  provider: pypi
  user: sunzhongmou
  password:
    secure: CHBGEMewUaHTnZhVqYmHxBv0ptD8QliZh7qbTfzzmnarQxUij61DQJiwWkBYMvV8ZJCFa9JNtJkSUDKmnt+wvHd0JLLAAIIe1Y2g222631B36wyBKXJ0mV+K4pCxf7LZWZi63IJUlHsj6JPH5k4IHTlGvm/vj9DAIEXDH1rO4nPSl6ovUv+DMkmjEgoz2Ak7t3TqTLX+x6emqgdT6LVcACrduqrw83lEeppieTl/qHy/rDCzXJoHd82zBaZvD1TMrj60CTYVIpLx4jOXqoHknDbZnpKEbSYrpXFk0xjjDAeIHuleeJKnMgZH4+sxT2qJ9j2oDp8XmFswSiODj1HKkEMSPpU4JfCw6EgYmpoTNBxLJBiFCx9/mTZTBQGqWkKLuWkTXgvwwUzQ1y19CMlgzy6foHPAeGSxs58o/viXVHrv0I2gMM3HEhX/q5tfrov9xaI0z0qATUYI1pskIxKvA5o0qCkXsLSQT32FKHo9+cASWXajQMPE8yMPVjZTGyFiBrpqTLeM6tLSBJAeNugvKpfkH3awKZcHYQvzqqVT1Sp7xFRQgrUMXYfgBPZvGVfxeiJHCKsR5wj6NbNn39PDMClvg2r1hOcJbh7/5zvJn/iVG3hXHK2PGpA7ZkqIggvU+6NuB3HGgUjQaOYfy7GkiITiSAHknCSg4Gk8zSbI5lQ=
  on:
    python: 2.7
